import { z } from "zod";

export const form5Schema = z.object({
  surname: z.string().nullable().optional(),
  firstName: z.string().nullable().optional(),
  fatherName: z.string().nullable().optional(),
  branchDept: z.string().nullable().optional(),
  yearLevel: z.string().nullable().optional(),
  diplomaFyDsy: z.string().nullable().optional(),
  permanentAddress: z.string().nullable().optional(),
  permanentCity: z.string().nullable().optional(),
  permanentPin: z.string().nullable().optional(),
  localAddress: z.string().nullable().optional(),
  localCity: z.string().nullable().optional(),
  localPin: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  dateOfBirth: z.string().nullable().optional(),
  gender: z.string().nullable().optional(),
  bloodGroup: z.string().nullable().optional(),
  studentMobileNo: z.string().nullable().optional(),
  parentsTelNo: z.string().nullable().optional(),
  castCategory: z.string().nullable().optional(),
  admissionReceiptNo: z.string().nullable().optional(),
  admissionDate: z.string().nullable().optional(),
  photoFileRef: z.string().nullable().optional(),
  signatureRef: z.string().nullable().optional(),
  dateField: z.string().nullable().optional(),
  adminOfficerAccountantSignRef: z.string().nullable().optional(),
  libraryMembershipIdCardNo: z.string().nullable().optional(),
  remark: z.string().nullable().optional(),
  librarianSignRef: z.string().nullable().optional(),
  rulesAgreedYn: z.boolean().nullable().optional(),
  rulesAgreedAt: z.string().nullable().optional(),
});

export type Form5Values = z.infer<typeof form5Schema>;

export const FORM5_DEFAULT_VALUES: Form5Values = {
  surname: null,
  firstName: null,
  fatherName: null,
  branchDept: null,
  yearLevel: null,
  diplomaFyDsy: null,
  permanentAddress: null,
  permanentCity: null,
  permanentPin: null,
  localAddress: null,
  localCity: null,
  localPin: null,
  email: null,
  dateOfBirth: null,
  gender: null,
  bloodGroup: null,
  studentMobileNo: null,
  parentsTelNo: null,
  castCategory: null,
  admissionReceiptNo: null,
  admissionDate: null,
  photoFileRef: null,
  signatureRef: null,
  dateField: null,
  adminOfficerAccountantSignRef: null,
  libraryMembershipIdCardNo: null,
  remark: null,
  librarianSignRef: null,
  rulesAgreedYn: null,
  rulesAgreedAt: null,
};
