import { z } from "zod";

export const form1Schema = z.object({
  // ── Student shared / profile fields ──
  fullNameSurname: z.string().nullable().optional(),
  fullNameFirst: z.string().nullable().optional(),
  fullNameFather: z.string().nullable().optional(),
  fatherName: z.string().nullable().optional(),
  motherName: z.string().nullable().optional(),
  dateOfBirth: z.string().nullable().optional(),
  bloodGroup: z.string().nullable().optional(),
  gender: z.string().nullable().optional(),
  religionCaste: z.string().nullable().optional(),
  contactTelNo: z.string().nullable().optional(),
  mobileNo: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  aadharNo: z.string().nullable().optional(),
  panNo: z.string().nullable().optional(),

  // ── Address fields ──
  correspondenceAddress: z.string().nullable().optional(),
  correspondencePin: z.string().nullable().optional(),
  correspondenceTelNo: z.string().nullable().optional(),
  permanentAddress: z.string().nullable().optional(),
  permanentPin: z.string().nullable().optional(),
  permanentTelNo: z.string().nullable().optional(),

  // ── Admission details ──
  branchCourse: z.string().nullable().optional(),
  admissionQuota: z.string().nullable().optional(),
  admissionCategory: z.string().nullable().optional(),
  admissionYearStart: z.coerce.number().int().nullable().optional(),
  admissionYearEnd: z.coerce.number().int().nullable().optional(),
  homeUniversity: z.string().nullable().optional(),
  motherTongue: z.string().nullable().optional(),

  // ── SSC Marks ──
  sscMarksEnglishObtained: z.coerce.number().nullable().optional(),
  sscMarksEnglishOutOf: z.coerce.number().nullable().optional(),
  sscMarksMathsObtained: z.coerce.number().nullable().optional(),
  sscMarksMathsOutOf: z.coerce.number().nullable().optional(),
  sscGrandTotalObtained: z.coerce.number().nullable().optional(),
  sscGrandTotalOutOf: z.coerce.number().nullable().optional(),
  sscPercentage: z.coerce.number().nullable().optional(),
  sscYearOfPassing: z.coerce.number().int().nullable().optional(),

  // ── HSC Marks ──
  hscPhysicsObtained: z.coerce.number().nullable().optional(),
  hscPhysicsOutOf: z.coerce.number().nullable().optional(),
  hscChemistryObtained: z.coerce.number().nullable().optional(),
  hscChemistryOutOf: z.coerce.number().nullable().optional(),
  hscMathsObtained: z.coerce.number().nullable().optional(),
  hscMathsOutOf: z.coerce.number().nullable().optional(),
  hscPcmTotalObtained: z.coerce.number().nullable().optional(),
  hscPcmTotalOutOf: z.coerce.number().nullable().optional(),
  hscGrandTotalObtained: z.coerce.number().nullable().optional(),
  hscGrandTotalOutOf: z.coerce.number().nullable().optional(),
  hscYearOfPassing: z.coerce.number().int().nullable().optional(),

  // ── CET Marks ──
  cetPhysicsObtained: z.coerce.number().nullable().optional(),
  cetPhysicsOutOf: z.coerce.number().nullable().optional(),
  cetChemistryObtained: z.coerce.number().nullable().optional(),
  cetChemistryOutOf: z.coerce.number().nullable().optional(),
  cetMathsObtained: z.coerce.number().nullable().optional(),
  cetMathsOutOf: z.coerce.number().nullable().optional(),
  cetPcmTotalObtained: z.coerce.number().nullable().optional(),
  cetPcmTotalOutOf: z.coerce.number().nullable().optional(),
  cetExamSeatNo: z.string().nullable().optional(),
  cetMeritNo: z.string().nullable().optional(),
  aieeeMarks: z.string().nullable().optional(),

  // ── Diploma ──
  diplomaMarksObtained: z.coerce.number().nullable().optional(),
  diplomaMarksOutOf: z.coerce.number().nullable().optional(),
  diplomaBranchCourse: z.string().nullable().optional(),
  diplomaBteEnrollmentNo: z.string().nullable().optional(),
  diplomaYearOfPassing: z.coerce.number().int().nullable().optional(),

  // ── Additional ──
  annualIncomeOfParent: z.coerce.number().nullable().optional(),
  dateField: z.string().nullable().optional(),
  placeField: z.string().nullable().optional(),
  signatureStudentRef: z.string().nullable().optional(),
  signatureParentRef: z.string().nullable().optional(),

  // ── Office Use Only ──
  officeUseEligibleFor: z.string().nullable().optional(),
  officeUseBranch: z.string().nullable().optional(),
});

export type Form1Values = z.infer<typeof form1Schema>;

export const FORM1_DEFAULT_VALUES: Form1Values = {
  fullNameSurname: null,
  fullNameFirst: null,
  fullNameFather: null,
  fatherName: null,
  motherName: null,
  dateOfBirth: null,
  bloodGroup: null,
  gender: null,
  religionCaste: null,
  contactTelNo: null,
  mobileNo: null,
  email: null,
  aadharNo: null,
  panNo: null,
  correspondenceAddress: null,
  correspondencePin: null,
  correspondenceTelNo: null,
  permanentAddress: null,
  permanentPin: null,
  permanentTelNo: null,
  branchCourse: null,
  admissionQuota: null,
  admissionCategory: null,
  admissionYearStart: 2026,
  admissionYearEnd: 2030,
  homeUniversity: null,
  motherTongue: null,
  sscMarksEnglishObtained: null,
  sscMarksEnglishOutOf: 100,
  sscMarksMathsObtained: null,
  sscMarksMathsOutOf: 100,
  sscGrandTotalObtained: null,
  sscGrandTotalOutOf: 500,
  sscPercentage: null,
  sscYearOfPassing: null,
  hscPhysicsObtained: null,
  hscPhysicsOutOf: 100,
  hscChemistryObtained: null,
  hscChemistryOutOf: 100,
  hscMathsObtained: null,
  hscMathsOutOf: 100,
  hscPcmTotalObtained: null,
  hscPcmTotalOutOf: 300,
  hscGrandTotalObtained: null,
  hscGrandTotalOutOf: 600,
  hscYearOfPassing: null,
  cetPhysicsObtained: null,
  cetPhysicsOutOf: 100,
  cetChemistryObtained: null,
  cetChemistryOutOf: 100,
  cetMathsObtained: null,
  cetMathsOutOf: 100,
  cetPcmTotalObtained: null,
  cetPcmTotalOutOf: 100,
  cetExamSeatNo: null,
  cetMeritNo: null,
  aieeeMarks: null,
  diplomaMarksObtained: null,
  diplomaMarksOutOf: null,
  diplomaBranchCourse: null,
  diplomaBteEnrollmentNo: null,
  diplomaYearOfPassing: null,
  annualIncomeOfParent: null,
  dateField: null,
  placeField: null,
  signatureStudentRef: null,
  signatureParentRef: null,
  officeUseEligibleFor: null,
  officeUseBranch: null,
};
