import { z } from "zod";

export const form3Schema = z.object({
  courseName: z.string().nullable().optional(),
  courseYear: z.string().nullable().optional(),
  applicantType: z.string().nullable().optional(),
  nationality: z.string().nullable().optional(),
  religion: z.string().nullable().optional(),
  categoryTick: z.string().nullable().optional(),
  belongsToReservedYn: z.boolean().nullable().optional(),
  physicallyDisabledYn: z.boolean().nullable().optional(),
  physicallyDisabledType: z.string().nullable().optional(),

  qualCourseName: z.string().nullable().optional(),
  qualDuration: z.string().nullable().optional(),
  qualUniversity: z.string().nullable().optional(),
  qualCollegeDept: z.string().nullable().optional(),
  qualSeatNo: z.string().nullable().optional(),
  qualMonthYearPassing: z.string().nullable().optional(),
  qualPercentage: z.coerce.number().nullable().optional(),
  qualClassGrade: z.string().nullable().optional(),

  gapLastExamName: z.string().nullable().optional(),
  gapSeatNo: z.string().nullable().optional(),
  gapMonthYearPassing: z.string().nullable().optional(),
  gapPercentage: z.coerce.number().nullable().optional(),
  gapClassGrade: z.string().nullable().optional(),

  minorityYn: z.boolean().nullable().optional(),
  minorityLinguistic: z.boolean().nullable().optional(),
  minorityReligion: z.boolean().nullable().optional(),

  signatureCandidateRef: z.string().nullable().optional(),

  officeReceiptNo: z.string().nullable().optional(),
  officeDate: z.string().nullable().optional(),
  officeEligibleStatus: z.string().nullable().optional(),
  officeAsst: z.string().nullable().optional(),
  officeSrAsst: z.string().nullable().optional(),
  officeOsRegistrarHod: z.string().nullable().optional(),
});

export type Form3Values = z.infer<typeof form3Schema>;

export const FORM3_DEFAULT_VALUES: Form3Values = {
  courseName: null,
  courseYear: null,
  applicantType: null,
  nationality: null,
  religion: null,
  categoryTick: null,
  belongsToReservedYn: null,
  physicallyDisabledYn: null,
  physicallyDisabledType: null,
  qualCourseName: null,
  qualDuration: null,
  qualUniversity: null,
  qualCollegeDept: null,
  qualSeatNo: null,
  qualMonthYearPassing: null,
  qualPercentage: null,
  qualClassGrade: null,
  gapLastExamName: null,
  gapSeatNo: null,
  gapMonthYearPassing: null,
  gapPercentage: null,
  gapClassGrade: null,
  minorityYn: null,
  minorityLinguistic: null,
  minorityReligion: null,
  signatureCandidateRef: null,
  officeReceiptNo: null,
  officeDate: null,
  officeEligibleStatus: null,
  officeAsst: null,
  officeSrAsst: null,
  officeOsRegistrarHod: null,
};
